---
title: "R_code_to_Rmd"
author: "Suman"
date: "`r format(Sys.time(), '$%B$ $%d$일, $%Y$년')`"
output: 
    html_document:
        theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

## R code 삽입 방법 

### R 코드 Chunk로 삽입

echo 옵션 기능 확인
```{r testcodeWtrue, echo=TRUE}
a <- c(1:5)
a 
```

```{r testcodeWfalse, echo=FALSE}
a <- c(1:5)
a 
```

eval 옵션

``` {r testcodeEvalTrue, eval=TRUE}
result1 <- mean(a)
```


``` {r testcodeEvalFalse, eval=FALSE}
result2 <- median(a)
```

```{r}
result1
```


resulthide 옵션

```{r testcodeResultoption, eval=TRUE, message=FALSE, warning=FALSE, results='hide'}
b <- c(1:100)
b
```



### 본문 안에 삽입

본문을 작성 중입니다. 앞에서 입력한 벡터 a의 평균은 $`r result1`$ 입니다. 


```{r message=FALSE, warning=FALSE}
library(ggplot2)

ggplot(mpg) +
 aes(x = fl, y = cyl, fill = cty, colour = class, size = displ) +
 geom_boxplot() +
 scale_fill_gradient() +
 scale_color_hue() +
 theme_minimal() +
 facet_wrap(vars(year))

```
